# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.acquisti.ordineAC.web.OrdineAcquistoEstrattoFormModifier', 'it.istech.thip.acquisti.ordineAC.web.YOrdineAcquistoEstrattoFormModifier', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.acquisti.ordineAC.web.OrdineTestataAcquistoEstrattoFormActionAdapter', 'it.istech.thip.acquisti.ordineAC.web.YOrdineTestataAcquistoEstrattoFormActionAdapter', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.acquisti.ordineAC.OrdineAcquistoRigaPrm', 'it.istech.thip.acquisti.ordineAC.YOrdineAcquistoRigaPrm', '0', 'N');
 	INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.acquisti.documentoAC.DocumentoAcqRigaPrm','it.istech.thip.acquisti.documentoAC.YDocumentoAcqRigaPrm', '0', 'N');
